version: '3'
services:
  consent-manager:
    image: "ganesan92/consent-manager:${CM_IMAGE_TAG}"
    ports:
      - "9051:8000"
    environment:
      - Auth_Token=${Auth_Token}
      - Client_Registry_Url=${Client_Registry_Url}
      - User_Service_Url=${User_Service_Url}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CONSENT_MANAGER_DB_NAME=${CONSENT_MANAGER_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_CONNECTION_POOL_SIZE=${DB_CONNECTION_POOL_SIZE}
      - GATEWAY_BASE_URL=${GATEWAY_BASE_URL}
    networks:
      - consent-manager
networks:
  consent-manager:
    driver: bridge