version: '3'
services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "HJKLSDFGHJKLMBZSFXFZD"
    ports:
      - "5672:5672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:rw"
      - "./volumes/rabbitmq/rabbit1/data:/var/lib/rabbitmq:rw"