version: '3'
services:
  consent-manager:
    build: .
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      CONSENTMANAGER_CLIENTREGISTRY_XAUTHTOKEN: "ada9c204-e571-4248-925b-7a1034ed30cb"
      CONSENTMANAGER_KEYCLOAK_CLIENTSECRET: "ada9c204-e571-4248-925b-7a1034ed30cb"
    depends_on:
      - otp
      - client-registry

  otp:
    image: "ganesan92/otp-service:latest"
    environment:
      "ConnectionStrings:DefaultConnection": "Host=postgres;Port=5432;Username=postgres;Password=password;Database=otpservice;"
    ports:
    - "5000:80"

  client-registry:
    image: "ganesan92/client-registry:f056f2c"
    ports:
      - "8080:8080"
    environment:
      profile: dev
      CENTRALREGISTRY_IDENTITY_URL: "http://keycloak:8080/auth/"
      CENTRALREGISTRY_IDENTITY_REALM: "central-registry"
      CENTRALREGISTRY_HOST: "http://keycloak:8080"