version: '3'
services:
  redis:
    image: 'redis:6.0-rc3'
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD
volumes:
  redis_data:
    driver: local
