openapi: 3.0.0
info:
  version: 0.0.1
  title: Health Information Consent Manager
  description: >
    Entity which provides health information aggregation services to customers of healthcare services.
    It enables customers to fetch their health information from one or more Health Information Providers
    (e.g., Hospitals, Diagnostic Labs, Medical Device Companies), based on their explicit Consent and to share such
    aggregated information with Health Information Users i.e. entities in need of such data (e.g., Insurers,
    Doctors, Medical Researchers).

servers:
  - url: http://localhost:8000
    description: Dev

tags:
  - name: link

paths:
  /patients/discover:
    post:
      tags:
        - link
      summary: Discover patient
      description: >
        Return only one patient record with (potentially masked) associated care contexts
        1. **At least one of the verified identifier matches.**
        2. **Filter out records using unverified, firstName, secondName, gender and dob
        if there are more than one patient records found from step 1.**
      operationId: discoverPatient
      parameters:
        - $ref: "#/components/parameters/authorization"
      requestBody:
        required: true
        description: A object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientDiscoveryRequest'
      responses:
        '200':
          description: Found a patient.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientDiscoveryResponse'

components:
  parameters:
    authorization:
      name: Authorization
      in: header
      description: Bearer token which was issued after successful login.
      schema:
        type: string

  schemas:
    PatientDiscoveryResponse:
      type: object
      properties:
        patient:
          $ref: '#/components/schemas/Patient'

    Patient:
      type: object
      properties:
        referenceNumber:
          type: string
        display:
          type: string
        careContexts:
          type: array
          items:
            $ref: '#/components/schemas/CareContext'

    CareContext:
      type: object
      properties:
        referenceNumber:
          type: string
        display:
          type: string
      xml:
        name: Tag

    PatientDiscoveryRequest:
      type: object
      properties:
        hipId:
          type: string
          description: Identifier of the health information provider where patient record needs to be looked up.