openapi: 3.0.0
info:
  version: 0.0.1
  title: Health Information Consent Manager
  description: >
    Entity which provides health information aggregation services to customers of healthcare services.
    It enables customers to fetch their health information from one or more Health Information Providers
    (e.g., Hospitals, Diagnostic Labs, Medical Device Companies), based on their explicit Consent and to share such
    aggregated information with Health Information Users i.e. entities in need of such data (e.g., Insurers,
    Doctors, Medical Researchers).

servers:
  - url: http://localhost:8000
    description: Dev

tags:
  - name: link

paths:
  /patients/discover:
    post:
      tags:
        - link
      summary: Discover patient
      description: >
        Return only one patient record with (potentially masked) associated care contexts
        1. **At least one of the verified identifier matches.**
        2. **Filter out records using unverified, firstName, secondName, gender and dob
        if there are more than one patient records found from step 1.**
      operationId: discoverPatient
      parameters:
        - $ref: "#/components/parameters/authorization"
      requestBody:
        required: true
        description: A object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientDiscoveryRequest'
      responses:
        '200':
          description: Found a patient.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientDiscoveryResponse'

  /patients/link:
    post:
      tags:
        - link
      summary: Link patient's care contexts
      description: >
        Links care contexts associated with only one patient
          1. **Validate account reference number and care context reference number**
          2. **Before linking, HIP needs to authenticate the request with the patient(Ex: OTP verification)**
          3. **Communicate the mode of authentication of a successful request with Consent Manager**
      operationId: linkPatient
      parameters:
        - $ref: "#/components/parameters/authorization"
      requestBody:
        required: true
        description: A object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientLinkReferenceRequest'
      responses:
        '200':
          description: A successful link request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientLinkReferenceResponse'

  /patients/link/{linkRefNumber}:
    post:
      tags:
        - link
      summary: Link Authenticates the token submitted by Consent Manager and links the account if authentication issuccessful.
      description: >
        Returns a list of linked care contexts with patient reference number.
          1. **Validate linked account reference number**
          2. **Validate if the token sent from Consent Manager is same as the one generated by HIP**
          3. **Verify whether same Consent Manager which made the link request is sending the token**
          4. **Returns a list of unmasked linked care contexts with patient reference number**
      operationId: linkPatient
      parameters:
        - $ref: "#/components/parameters/authorization"
      requestBody:
        required: true
        description: A object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientLinkRequest'
      responses:
        '200':
          description: List of linked care contexts of a patient with patient reference number.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientLinkResponse'

components:
  parameters:
    authorization:
      name: Authorization
      in: header
      description: Bearer token which was issued after successful login.
      schema:
        type: string

  schemas:
    PatientDiscoveryResponse:
      type: object
      properties:
        patient:
          $ref: '#/components/schemas/Patient'

    Patient:
      type: object
      properties:
        referenceNumber:
          type: string
        display:
          type: string
        careContexts:
          type: array
          items:
            $ref: '#/components/schemas/CareContextRepresentation'

    CareContextRepresentation:
      type: object
      properties:
        referenceNumber:
          type: string
        display:
          type: string
      xml:
        name: CareContextRepresentation

    CareContext:
      type: object
      properties:
        referenceNumber:
          type: string
      xml:
        name: CareContext

    PatientDiscoveryRequest:
      type: object
      properties:
        hipId:
          type: string
          description: Identifier of the health information provider where patient record needs to be looked up.

    PatientLinkReferenceRequest:
      type: object
      properties:
        consentManagerUserID:
          type: string
        patientReferenceNumber:
          type: string
        careContexts:
          type: array
          items:
            $ref: '#/components/schemas/CareContext'
          xml:
            name: careContexts
            wrapped: true
      xml:
        name: PatientLinkReferenceRequest

    PatientLinkReferenceResponse:
      type: object
      required:
        - referenceNumber
        - authenticationType
      properties:
        referenceNumber:
          type: string
        authenticationType:
          type: string
          enum: ['DIRECT', 'MEDIATED']
        meta:
          $ref: '#/components/schemas/Meta'

    Meta:
      type: object
      required:
        - mode
        - value
      properties:
        communicationMedium:
          type: string
          enum: ['M0BILE', 'EMAIL']
        communicationHint:
          type: string
        communicationExpiry:
          type: string
          example: "2019-12-30T12:01:55Z"
      xml:
        name: Meta

    PatientLinkRequest:
      type: object
      properties:
        token:
          type: string

    PatientLinkResponse:
      type: object
      required:
        - referenceNumber
        - careContexts
      properties:
        referenceNumber:
          type: string
        careContexts:
          type: array
          items:
            $ref: '#/components/schemas/CareContextRepresentation'

