@startuml
entity HIU
entity CR
entity HDCM
entity HIP

header Thoughtworks
title Data Transfer Request

HIU -> CR: 1. Authentication Request
CR --> HIU: 1. Authentication Response

HIU -> HDCM: 2. Data Transfer Request
rnote over HIU
Consent Artefact ID
Encryption Keys
Call Back URL
end note
rnote over HDCM
 Validates following:

   1. Consent Artefact
   2. Check Identity of HIU

end note
note right of HIU
Transaction ID
end note
HDCM --> HIU: 2. Request Accepted

HDCM -> CR: 3. Authentication Request
CR --> HDCM: 3. Authentication Response

HDCM -> HIP: 4. Data Transfer Request with Transaction ID
rnote over HIP
Validates following:
    1. Consent Artefact

Gets:
    HIU Callback URL

end note
HIP -> HDCM: 4. Request Accepted


HIP --> HIP: Prepares the data
@enduml