name: Auto sync

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/ProjectEKA/consent-manager.git"
          source_branch: "master"
          destination_branch: "eka_sync_branch"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "eka_sync_branch"
          destination_branch: "master"
          pr_body: ":crown: *An automated PR*"
          pr_title: "Pulling ${{ github.ref }} into master"
          github_token: ${{ secrets.GITHUB_TOKEN }}