name: Auto sync

on:
  schedule:
    - cron: "* */6 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/ProjectEKA/consent-manager.git"
          source_branch: "master"
          destination_branch: "new_branch"
          github_token: ${{ secrets.GITHUB_TOKEN }}
